version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  medicate-rust:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - RUST_LOG=info
    depends_on:
      - redis

volumes:
  redis_data: 